/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as LogowanieRouteImport } from './routes/logowanie'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as PlatnoscRouteImport } from './routes/platnosc'
import { Route as PotwierdzenieRouteImport } from './routes/potwierdzenie'
import { Route as SklepRouteImport } from './routes/sklep'
import { Route as ZamowienieRouteImport } from './routes/zamowienie'
import { Route as AdminZamowieniaOrderIdRouteImport } from './routes/admin.zamowienia.$orderId'
import { Route as KontoZamowieniaOrderIdRouteImport } from './routes/konto.zamowienia.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const LogowanieRoute = LogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatnoscRoute = PlatnoscRouteImport.update({
  id: '/platnosc',
  path: '/platnosc',
  getParentRoute: () => rootRouteImport,
} as any)
const PotwierdzenieRoute = PotwierdzenieRouteImport.update({
  id: '/potwierdzenie',
  path: '/potwierdzenie',
  getParentRoute: () => rootRouteImport,
} as any)
const SklepRoute = SklepRouteImport.update({
  id: '/sklep',
  path: '/sklep',
  getParentRoute: () => rootRouteImport,
} as any)
const ZamowienieRoute = ZamowienieRouteImport.update({
  id: '/zamowienie',
  path: '/zamowienie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZamowieniaOrderIdRoute = AdminZamowieniaOrderIdRouteImport.update({
  id: '/zamowienia/$orderId',
  path: '/zamowienia/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const KontoZamowieniaOrderIdRoute = KontoZamowieniaOrderIdRouteImport.update({
  id: '/zamowienia/$orderId',
  path: '/zamowienia/$orderId',
  getParentRoute: () => KontoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/konto': typeof KontoRouteWithChildren
  '/logowanie': typeof LogowanieRoute
  '/oferta': typeof OfertaRoute
  '/platnosc': typeof PlatnoscRoute
  '/potwierdzenie': typeof PotwierdzenieRoute
  '/sklep': typeof SklepRoute
  '/zamowienie': typeof ZamowienieRoute
  '/admin/zamowienia/$orderId': typeof AdminZamowieniaOrderIdRoute
  '/konto/zamowienia/$orderId': typeof KontoZamowieniaOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/konto': typeof KontoRouteWithChildren
  '/logowanie': typeof LogowanieRoute
  '/oferta': typeof OfertaRoute
  '/platnosc': typeof PlatnoscRoute
  '/potwierdzenie': typeof PotwierdzenieRoute
  '/sklep': typeof SklepRoute
  '/zamowienie': typeof ZamowienieRoute
  '/admin/zamowienia/$orderId': typeof AdminZamowieniaOrderIdRoute
  '/konto/zamowienia/$orderId': typeof KontoZamowieniaOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/konto': typeof KontoRouteWithChildren
  '/logowanie': typeof LogowanieRoute
  '/oferta': typeof OfertaRoute
  '/platnosc': typeof PlatnoscRoute
  '/potwierdzenie': typeof PotwierdzenieRoute
  '/sklep': typeof SklepRoute
  '/zamowienie': typeof ZamowienieRoute
  '/admin/zamowienia/$orderId': typeof AdminZamowieniaOrderIdRoute
  '/konto/zamowienia/$orderId': typeof KontoZamowieniaOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faq'
    | '/kontakt'
    | '/konto'
    | '/logowanie'
    | '/oferta'
    | '/platnosc'
    | '/potwierdzenie'
    | '/sklep'
    | '/zamowienie'
    | '/admin/zamowienia/$orderId'
    | '/konto/zamowienia/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faq'
    | '/kontakt'
    | '/konto'
    | '/logowanie'
    | '/oferta'
    | '/platnosc'
    | '/potwierdzenie'
    | '/sklep'
    | '/zamowienie'
    | '/admin/zamowienia/$orderId'
    | '/konto/zamowienia/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faq'
    | '/kontakt'
    | '/konto'
    | '/logowanie'
    | '/oferta'
    | '/platnosc'
    | '/potwierdzenie'
    | '/sklep'
    | '/zamowienie'
    | '/admin/zamowienia/$orderId'
    | '/konto/zamowienia/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FaqRoute: typeof FaqRoute
  KontaktRoute: typeof KontaktRoute
  KontoRoute: typeof KontoRouteWithChildren
  LogowanieRoute: typeof LogowanieRoute
  OfertaRoute: typeof OfertaRoute
  PlatnoscRoute: typeof PlatnoscRoute
  PotwierdzenieRoute: typeof PotwierdzenieRoute
  SklepRoute: typeof SklepRoute
  ZamowienieRoute: typeof ZamowienieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logowanie': {
      id: '/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof LogowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platnosc': {
      id: '/platnosc'
      path: '/platnosc'
      fullPath: '/platnosc'
      preLoaderRoute: typeof PlatnoscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/potwierdzenie': {
      id: '/potwierdzenie'
      path: '/potwierdzenie'
      fullPath: '/potwierdzenie'
      preLoaderRoute: typeof PotwierdzenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sklep': {
      id: '/sklep'
      path: '/sklep'
      fullPath: '/sklep'
      preLoaderRoute: typeof SklepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zamowienie': {
      id: '/zamowienie'
      path: '/zamowienie'
      fullPath: '/zamowienie'
      preLoaderRoute: typeof ZamowienieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zamowienia/$orderId': {
      id: '/admin/zamowienia/$orderId'
      path: '/zamowienia/$orderId'
      fullPath: '/admin/zamowienia/$orderId'
      preLoaderRoute: typeof AdminZamowieniaOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/konto/zamowienia/$orderId': {
      id: '/konto/zamowienia/$orderId'
      path: '/zamowienia/$orderId'
      fullPath: '/konto/zamowienia/$orderId'
      preLoaderRoute: typeof KontoZamowieniaOrderIdRouteImport
      parentRoute: typeof KontoRoute
    }
  }
}

interface AdminRouteChildren {
  AdminZamowieniaOrderIdRoute: typeof AdminZamowieniaOrderIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminZamowieniaOrderIdRoute: AdminZamowieniaOrderIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface KontoRouteChildren {
  KontoZamowieniaOrderIdRoute: typeof KontoZamowieniaOrderIdRoute
}

const KontoRouteChildren: KontoRouteChildren = {
  KontoZamowieniaOrderIdRoute: KontoZamowieniaOrderIdRoute,
}

const KontoRouteWithChildren = KontoRoute._addFileChildren(KontoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FaqRoute: FaqRoute,
  KontaktRoute: KontaktRoute,
  KontoRoute: KontoRouteWithChildren,
  LogowanieRoute: LogowanieRoute,
  OfertaRoute: OfertaRoute,
  PlatnoscRoute: PlatnoscRoute,
  PotwierdzenieRoute: PotwierdzenieRoute,
  SklepRoute: SklepRoute,
  ZamowienieRoute: ZamowienieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
